<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WotLK.Launcher\WotLK.Launcher.csproj" />
    <ProjectReference Include="..\WotLK.Launcher.Installer\WotLK.Launcher.Installer.csproj" />
    <ProjectReference Include="..\WotLK.Launcher.Server\WotLK.Launcher.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
