[Service]
WorkingDirectory=/opt/hermesproxy-wotlk/releases/hermes-all-update-20260912
ExecStart=
ExecStart=/opt/hermesproxy-wotlk/releases/hermes-all-update-20260912/HermesProxy --config /opt/hermesproxy-wotlk/appsettings.atlas.json
