using System.Globalization;

namespace WotLK.Launcher.UI.V2.Localization;

internal static class LauncherLocalization
{
    internal const string FrenchLocale = "fr-FR";
    internal const string EnglishLocale = "en-US";

    private static readonly IReadOnlyDictionary<string, string> EnglishByFrench =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Jeu"] = "Game",
            ["Mises à jour"] = "Updates",
            ["Notes de version"] = "Release notes",
            ["Découvrez les dernières mises à jour, améliorations et corrections du launcher."] = "Discover the latest launcher updates, improvements, and fixes.",
            ["Brouillon en cours"] = "Draft in progress",
            ["Modifications locales"] = "Local changes",
            ["Voir les détails et les actions"] = "View details and actions",
            ["Voir les détails et les actions de cet addon"] = "View details and actions for this addon",
            ["Brouillon local"] = "Local draft",
            ["BROUILLON LOCAL"] = "LOCAL DRAFT",
            ["Interface repensée, lancement du jeu mieux encadré, présence des amis enrichie, compte et addons améliorés. Le profil et l’armurerie 3D sont présentés en aperçu local dans la dernière rubrique."] = "A redesigned interface, improved game launch checks, richer friend presence, and account and addon improvements. The profile and 3D armory are presented as a local preview in the final section.",
            ["Interface repensée, lancement du jeu mieux encadré, présence des amis enrichie, compte et addons améliorés. Le profil et l’armurerie 3D rejoignent le client public préparé pour la version 1.4.0."] = "A redesigned interface, improved game launch checks, richer friend presence, and account and addon improvements. The profile and 3D armory join the public client being prepared for version 1.4.0.",
            ["Launcher"] = "Launcher",
            ["Profil et compte"] = "Profile and account",
            ["Amis et présence"] = "Friends and presence",
            ["Paramètres et Windows"] = "Settings and Windows",
            ["Notes de version et mises à jour"] = "Release notes and updates",
            ["Corrections d’interaction"] = "Interaction fixes",
            ["Profil et armurerie 3D — aperçu local"] = "Profile and 3D armory — local preview",
            ["Profil et armurerie 3D"] = "Profile and 3D armory",
            ["Installation et distribution"] = "Installation and distribution",
            ["Le profil immersif et l’armurerie 3D sont intégrés au client public, accessibles depuis Gérer mon profil."] = "The immersive profile and 3D armory are integrated into the public client, accessible from Manage my profile.",
            ["Le launcher inclut les composants nécessaires au profil et à l’armurerie, sans installation manuelle d’outils supplémentaires."] = "The launcher includes the components required by the profile and armory, without manually installing additional tools.",
            ["Les personnages et leur équipement sont chargés à partir du compte connecté. L’armurerie donne accès uniquement aux personnages de ce compte."] = "Characters and their equipment are loaded for the signed-in account. The armory provides access only to characters belonging to that account.",
            ["Si le composant Microsoft WebView2 est absent ou trop ancien, le launcher installe automatiquement la version nécessaire à l’ouverture du profil."] = "If Microsoft WebView2 is missing or too old, the launcher automatically installs the version required to open the profile.",
            ["Refonte de la page Jeu et des pages Addons, Notes de version et Paramètres autour d’un décor de la Citadelle, d’un visuel panoramique du Roi-liche et de nouvelles surfaces bleues."] = "The Game, Addons, Release notes and Settings pages have been redesigned around an Icecrown Citadel backdrop, panoramic Lich King artwork and new blue surfaces.",
            ["Nouvelle typographie commune, textes secondaires plus contrastés et rendu du texte amélioré dans les pages, menus et fenêtres du launcher."] = "A consistent new typeface, higher-contrast secondary text and improved text rendering across launcher pages, menus and dialogs.",
            ["Barre de navigation allégée, accès aux amis par une icône et version du launcher regroupée dans les paramètres."] = "A cleaner navigation bar, an icon for opening friends, and the launcher version grouped with settings.",
            ["La fenêtre adopte un format fixe et peut être déplacée depuis la barre de navigation ou la marge supérieure vide."] = "The window now has a fixed size and can be dragged using the navigation bar or the empty top margin.",
            ["Les fenêtres de connexion, le menu du profil, les amis, le recadrage et le centre d’activité adoptent la même présentation. Les panneaux superposés masquent correctement le contenu placé derrière."] = "Sign-in dialogs, the profile menu, friends, image cropping and the activity center now share the same design. Overlays properly cover the content behind them.",
            ["Suppression des sous-titres, cadres de focus et infobulles d’action redondants. Les détails des textes tronqués et les raisons d’indisponibilité restent accessibles."] = "Redundant subtitles, focus boxes and action tooltips have been removed. Details for truncated text and reasons why actions are unavailable remain accessible.",
            ["L’état du serveur est affiché au-dessus du bouton Jouer et actualisé automatiquement."] = "Server status is displayed above the Play button and refreshed automatically.",
            ["Le bouton Jouer indique le lancement puis l’utilisation du jeu, et redevient disponible à sa fermeture."] = "The Play button indicates when the game is launching or running, and becomes available again when the game closes.",
            ["Lorsque le serveur est confirmé hors ligne, le bouton affiche Serveur indisponible et empêche le lancement. Le retour en ligne permet de jouer à nouveau ; les outils de maintenance restent accessibles."] = "When the server is confirmed offline, the button shows Server unavailable and prevents launching. Play becomes available again when the server returns online; maintenance tools remain accessible.",
            ["Les textes de progression du téléchargement et de la vérification disposent d’espaces séparés pour éviter leur superposition."] = "Download and verification progress labels have separate space to prevent overlapping.",
            ["Amélioration de la prise en charge des autorisations Windows lorsque le dossier du jeu n’est pas accessible en écriture."] = "Improved handling of Windows permissions when the game folder is not writable.",
            ["Les accès Gérer mon profil et Gérer mon compte sont séparés pour distinguer le profil public des réglages du compte."] = "Manage my profile and Manage my account are separate, distinguishing the public profile from account settings.",
            ["Ajout d’une bio et d’un statut personnel visibles sur le profil consulté par les amis."] = "A bio and personal status can be displayed on the profile viewed by friends.",
            ["Les photos de profil jusqu’à 25 Mo sont acceptées. Un clic sur l’avatar permet de choisir une photo, puis de la recadrer avec déplacement et zoom à la molette."] = "Profile pictures up to 25 MB are supported. Clicking the avatar lets you choose a picture, then crop it by repositioning it and zooming with the mouse wheel.",
            ["Correction de la cohérence entre le cadrage et l’aperçu, de la mise à jour de l’avatar après validation et de sa synchronisation après reconnexion."] = "Fixed consistency between cropping and preview, avatar updates after saving, and synchronization after signing in again.",
            ["Les pages Sécurité et Sessions, les champs de saisie et les états d’enregistrement ont été réorganisés pour rendre les actions plus lisibles."] = "Security and Sessions pages, input fields and saving states have been reorganized to make actions clearer.",
            ["L’état de vérification est indiqué à côté de l’adresse e-mail. L’avertissement apparaît uniquement lorsqu’une confirmation est nécessaire, et le champ de nouvelle adresse reste vide à l’ouverture."] = "Verification status is shown next to the email address. A warning appears only when confirmation is required, and the new-address field starts empty.",
            ["Une reconnexion depuis le même appareil ne crée plus de doublons dans les sessions. La déconnexion ramène à la connexion sans laisser le compte ni le jeu visibles derrière."] = "Signing in again from the same device no longer creates duplicate sessions. Signing out returns to the sign-in screen without leaving the account or game page visible behind it.",
            ["Liste d’amis réorganisée avec recherche, demandes d’amitié et informations de présence plus lisibles."] = "The friends list has been reorganized with search, friend requests and clearer presence information.",
            ["La présence distingue désormais Connecté au launcher et En jeu. Un ami peut apparaître en ligne même si aucun de ses personnages n’est connecté au jeu."] = "Presence now distinguishes Connected to launcher from In game. A friend can appear online even when none of their characters are in the game.",
            ["Le compteur, l’ordre des amis en ligne et la dernière présence prennent en compte la connexion au launcher."] = "The online count, online-friend ordering and last-seen information now account for launcher activity.",
            ["Un clic sur un ami ouvre sa photo, son pseudo, son statut, sa bio et ses personnages, avec leur classe, niveau, zone et dernière présence."] = "Clicking a friend opens their picture, display name, status, bio and characters, including class, level, zone and last-seen information.",
            ["Le personnage mis en avant n’est plus répété dans les autres personnages. Hors ligne, il est présenté comme Dernier personnage joué ; les icônes et couleurs de classe facilitent la lecture."] = "The featured character is no longer duplicated among other characters. When offline, it is labeled Last character played; class icons and colors improve readability.",
            ["Les nouvelles demandes d’ami sont notifiées. Une notification sonore, désactivable dans les paramètres, signale les connexions d’amis ; le passage du launcher au jeu ne déclenche pas une seconde notification."] = "New friend requests trigger notifications. A sound notification, which can be disabled in settings, announces friend connections; moving from the launcher into the game does not trigger a second notification.",
            ["Ajout d’une confirmation avant de retirer un ami, avec menus, sélection, retour à la liste et fermeture par Échap améliorés."] = "Removing a friend now requires confirmation, with improved menus, selection, return to the list and dismissal with Escape.",
            ["Catalogue plus compact, descriptions sur une ligne et versions abrégées. Les informations complètes restent accessibles dans les détails et les infobulles."] = "A more compact catalog, single-line descriptions and shortened versions. Full information remains available in details and tooltips.",
            ["La recherche conserve les espaces pendant la saisie, notamment pour les noms composés comme Deadly Boss."] = "Search now preserves spaces while typing, including multiword names such as Deadly Boss.",
            ["L’actualisation d’une fiche ne déplace plus le focus vers sa croix de fermeture."] = "Refreshing an addon details panel no longer moves focus to its close button.",
            ["La confirmation de suppression conserve le clavier dans sa fenêtre. Les libellés de filtre et de mise à jour du catalogue ont également été complétés en anglais."] = "The removal confirmation keeps keyboard focus inside its dialog. English translations for filter and catalog-update labels have also been completed.",
            ["Interface disponible en français et en anglais, avec changement de langue sans redémarrage."] = "The interface is available in French and English, with no restart required when switching languages.",
            ["Paramètres réorganisés, descriptions répétitives retirées et interrupteurs arrondis avec animation et curseur adaptés."] = "Settings have been reorganized, repeated descriptions removed, and rounded toggles now have suitable animations and cursors.",
            ["L’option Démarrer avec Windows lance désormais le launcher réduit dans la barre des tâches, sans prendre le focus. L’ancien réglage de démarrage est repris automatiquement."] = "Start with Windows now launches the launcher minimized to the taskbar without taking focus. The previous startup setting is migrated automatically.",
            ["Une seule instance du launcher est ouverte à la fois. Un second démarrage automatique ne remet pas la fenêtre existante au premier plan."] = "Only one launcher instance opens at a time. A second automatic startup does not bring the existing window to the foreground.",
            ["Le launcher reste accessible dans la zone de notification Windows. Selon le réglage choisi, fermer la fenêtre peut l’y ranger et retirer son bouton de la barre des tâches."] = "The launcher remains accessible in the Windows notification area. Depending on the selected setting, closing the window can move it there and remove its taskbar button.",
            ["L’onglet Notes de version dispose d’une page dédiée, avec les nouveautés regroupées par catégorie et les versions précédentes conservées."] = "The Release notes tab has a dedicated page, with changes grouped by category and previous versions retained.",
            ["Lecture des notes améliorée : texte plus grand, lignes moins longues et interligne plus aéré."] = "Release notes are easier to read, with larger text, shorter lines and more line spacing.",
            ["Un bouton vert apparaît dans la barre du haut lorsqu’une mise à jour du launcher est disponible. Il lance son installation et ouvre le suivi du téléchargement."] = "A green button appears in the top bar when a launcher update is available. It starts installation and opens download progress.",
            ["La version et l’état de mise à jour sont réunis sur une ligne dans les paramètres. Les états non vérifié, recherche en cours, à jour, mise à jour disponible et erreur sont distingués."] = "The version and update status share one line in settings. Not checked, checking, up to date, update available and error states are distinguished.",
            ["Sur l’écran d’authentification, Entrée respecte le champ ou le bouton utilisé et ne soumet plus la connexion depuis l’onglet Inscription."] = "On the authentication screen, Enter respects the active field or button and no longer submits sign-in from the registration tab.",
            ["Un clic en dehors du menu du profil conserve le focus sur le contrôle choisi. Dans l’interface principale, Tab parcourt les champs de saisie sans passer par les boutons, interrupteurs et lignes d’addons."] = "Clicking outside the profile menu keeps focus on the selected control. In the main interface, Tab moves through input fields without visiting buttons, toggles or addon rows.",
            ["Les formulaires du compte et le recadrage protègent les modifications en cours. Les erreurs, la progression et les boutons de validation restent visibles pendant l’enregistrement."] = "Account forms and cropping protect changes while they are being saved. Errors, progress and confirmation buttons remain visible during saving.",
            ["Aperçu réservé au client local pour cette préparation : le profil immersif et l’armurerie 3D doivent encore être intégrés au paquet public."] = "This preview is limited to the local client during preparation: the immersive profile and 3D armory still need to be integrated into the public package.",
            ["Consultation des personnages du compte avec recherche et sélection du personnage à afficher."] = "Browse account characters, search them and select which character to display.",
            ["Aperçu 3D animé reprenant l’apparence et l’équipement du personnage, avec rotation, zoom, recentrage, pause de l’animation et affichage des armes."] = "An animated 3D preview reflects the character’s appearance and equipment, with rotation, zoom, recentering, animation pause and weapon display controls.",
            ["Équipement présenté par emplacement, avec infobulles d’objets en français et en anglais. Les statistiques utilisent le dernier relevé serveur disponible et signalent les valeurs manquantes."] = "Equipment is displayed by slot, with item tooltips in French and English. Statistics use the latest available server snapshot and indicate missing values.",
            ["Édition de l’avatar, de la bio et du statut regroupée dans le profil. La photo, le nom et les textes de présentation sont agrandis."] = "Avatar, bio and status editing are grouped in the profile. The picture, name and profile text are larger.",
            ["Bannière personnalisée enregistrée localement pour chaque compte, avec import, remplacement, réinitialisation et aperçu avant validation."] = "A custom banner is saved locally for each account, with import, replacement, reset and preview before saving.",
            ["Recadrage de la bannière par déplacement de l’image, curseur et zoom à la molette de 100 à 300 %. Annuler conserve la bannière enregistrée."] = "Crop the banner by moving the image, using the slider or zooming with the mouse wheel from 100 to 300%. Canceling preserves the saved banner.",
            ["La barre de navigation apparaît au survol de toute la bannière, avatar compris, et commence à se masquer dès que le pointeur en sort. Elle reste accessible pendant l’utilisation de ses menus."] = "The navigation bar appears when hovering anywhere over the banner, including the avatar, and starts hiding as soon as the pointer leaves. It remains accessible while its menus are in use.",
            ["L’ouverture et la fermeture de l’édition du profil conservent le zoom et l’orientation de la caméra 3D. Un refus du sélecteur d’image ne laisse plus les boutons bloqués."] = "Opening and closing profile editing preserves the 3D camera’s zoom and orientation. A rejected image-picker request no longer leaves buttons stuck.",
            ["Ajustements après la 1.3.0"] = "Refinements after 1.3.0",
            ["Changements locaux depuis la version 1.3.0, non publiés."] = "Local changes since version 1.3.0, not yet published.",
            ["Lisibilité"] = "Readability",
            ["Profils d’amis"] = "Friend profiles",
            ["L’onglet du haut s’appelle Notes de version pour le distinguer des mises à jour du launcher."] = "The top tab is now called Release notes to distinguish it from launcher updates.",
            ["Dans les paramètres, la version et l’état de mise à jour sont réunis sur une ligne, sans cadres imbriqués."] = "Settings now show the version and update status on one line, without nested frames.",
            ["Les lignes du catalogue sont plus compactes et les descriptions restent sur une ligne."] = "Catalog rows are more compact, with descriptions kept on one line.",
            ["Les versions sont abrégées dans la liste ; leur détail complet reste accessible en infobulle et dans la fiche."] = "Versions are shortened in the list; full details remain available in tooltips and the addon details panel.",
            ["Les textes secondaires sont plus contrastés et plusieurs sous-titres redondants ont été retirés."] = "Secondary text has more contrast and several redundant subtitles have been removed.",
            ["Les notes de version utilisent un texte plus grand, des lignes moins longues et un interligne plus aéré."] = "Release notes use larger text, shorter lines and increased line spacing.",
            ["Le personnage mis en avant n’est plus répété dans la liste des autres personnages."] = "The featured character is no longer repeated in the other characters list.",
            ["Hors ligne, l’intitulé devient Dernier personnage joué au lieu de Personnage actif."] = "When offline, the heading changes from Active character to Last character played.",
            ["Les personnages affichent leur icône et leur couleur de classe, avec des informations secondaires plus lisibles."] = "Characters display their class icon and color, with more readable secondary information.",
            ["Recherche en cours…"] = "Checking…",
            ["Mise à jour en cours…"] = "Updating…",
            ["Vérification indisponible"] = "Check unavailable",
            ["Échec de la mise à jour"] = "Update failed",
            ["Installation externe"] = "External installation",
            ["DERNIER PERSONNAGE JOUÉ"] = "LAST CHARACTER PLAYED",
            ["AUTRES PERSONNAGES"] = "OTHER CHARACTERS",
            ["Guerrier"] = "Warrior",
            ["Paladin"] = "Paladin",
            ["Chasseur"] = "Hunter",
            ["Voleur"] = "Rogue",
            ["Prêtre"] = "Priest",
            ["Chevalier de la mort"] = "Death Knight",
            ["Chaman"] = "Shaman",
            ["Mage"] = "Mage",
            ["Démoniste"] = "Warlock",
            ["Druide"] = "Druid",
            ["niveau "] = "level ",
            ["Notes"] = "Notes",
            ["Addons"] = "Addons",
            ["ADDONS"] = "ADDONS",
            ["Amis"] = "Friends",
            ["AMIS"] = "FRIENDS",
            ["Paramètres"] = "Settings",
            ["Personnalisez votre expérience Atlas Launcher."] = "Customize your Atlas Launcher experience.",
            ["Configurez les paramètres de base du launcher."] = "Configure the launcher's basic settings.",
            ["Personnalisez le comportement et l’apparence d’Atlas Launcher."] = "Customize how Atlas Launcher looks and behaves.",
            ["Choisissez la langue d’affichage du launcher."] = "Choose the launcher's display language.",
            ["Lance automatiquement Atlas Launcher au démarrage de Windows."] = "Automatically launch Atlas Launcher when Windows starts.",
            ["Le launcher continuera de fonctionner dans la zone de notification."] = "The launcher will keep running in the notification area.",
            ["Général"] = "General",
            ["Notifications"] = "Notifications",
            ["Diagnostic"] = "Diagnostics",
            ["Aide et diagnostic"] = "Help and diagnostics",
            ["Réduire"] = "Minimize",
            ["Agrandir ou restaurer"] = "Maximize or restore",
            ["Réduire dans la zone de notification"] = "Minimize to the notification area",
            ["Ouvrir Atlas Launcher"] = "Open Atlas Launcher",
            ["Quitter"] = "Quit",
            ["Ouvrir"] = "Open",
            ["Version locale de test"] = "Local test version",
            ["Atlas Launcher · Prévisualisation V2"] = "Atlas Launcher · V2 Preview",
            ["LOCAL"] = "LOCAL",
            ["Arthas en ligne"] = "Arthas online",
            ["Arthas dégradé"] = "Arthas degraded",
            ["Arthas hors ligne"] = "Arthas offline",
            ["Serveur de jeu en ligne"] = "Game server online",
            ["Services de jeu dégradés"] = "Game services degraded",
            ["Serveur de jeu hors ligne"] = "Game server offline",
            ["Serveur indisponible"] = "Server unavailable",
            ["Vérification du serveur de jeu…"] = "Checking game server…",
            ["État du serveur de jeu indisponible"] = "Game server status unavailable",
            ["Serveur de jeu non vérifié"] = "Game server not checked",
            ["En ligne"] = "Online",
            ["EN LIGNE"] = "ONLINE",
            ["Connecté au launcher"] = "Online in the launcher",
            ["Hors ligne"] = "Offline",
            ["En jeu"] = "In game",
            ["Indisponible"] = "Unavailable",
            ["Chargement…"] = "Loading…",
            ["Activité"] = "Activity",
            ["Ouvrir le centre d’activité"] = "Open activity center",
            ["Ouvrir le panneau Amis"] = "Open Friends panel",
            ["Fermer le centre d’activité"] = "Close activity center",
            ["Fermer le panneau Amis"] = "Close Friends panel",
            ["Fermer le profil"] = "Close profile",
            ["Fermer"] = "Close",
            ["Bienvenue en Norfendre"] = "Welcome to Northrend",
            ["Bienvenue"] = "Welcome",
            ["en Norfendre"] = "to Northrend",
            ["Votre aventure vous attend"] = "Your adventure awaits",
            ["Votre aventure vous attend."] = "Your adventure awaits.",
            ["Raids épiques"] = "Epic raids",
            ["Communauté active"] = "Active community",
            ["L’expérience WotLK Classic"] = "The WotLK Classic experience",
            ["ROYAUME ARTHAS"] = "ARTHAS REALM",
            ["Jouer"] = "Play",
            ["En cours de lancement"] = "Launching game",
            ["Jeu en cours de lancement"] = "Launching game",
            ["Jeu en cours d’utilisation"] = "Game running",
            ["Installation"] = "Install",
            ["Installer"] = "Install",
            ["Mettre à jour"] = "Update",
            ["Mettre à jour Atlas Launcher"] = "Update Atlas Launcher",
            ["Réessayer"] = "Try again",
            ["Vérifier"] = "Verify",
            ["Vérifier et réparer"] = "Verify and repair",
            ["Ouvrir le dossier"] = "Open folder",
            ["Parcourir"] = "Browse",
            ["Client non installé"] = "Client not installed",
            ["Client prêt"] = "Client ready",
            ["Client prêt · non vérifié"] = "Client ready · not verified",
            ["Client prêt · à jour"] = "Client ready · up to date",
            ["Client prêt · mise à jour disponible"] = "Client ready · update available",
            ["Mise à jour disponible"] = "Update available",
            ["Vérification en cours"] = "Verification in progress",
            ["Vérification en cours…"] = "Verification in progress…",
            ["Téléchargement en cours"] = "Downloading",
            ["Installation en cours"] = "Installing",
            ["Annuler"] = "Cancel",
            ["Annuler l’opération"] = "Cancel operation",
            ["Ouvrir l’élément associé"] = "Open related item",
            ["OPÉRATIONS EN COURS"] = "CURRENT OPERATIONS",
            ["RÉCENT"] = "RECENT",
            ["EN COURS"] = "IN PROGRESS",
            ["EN ATTENTE"] = "PENDING",
            ["En attente"] = "Pending",
            ["Aucune activité récente"] = "No recent activity",
            ["Les installations, mises à jour et réparations apparaîtront ici."] = "Installations, updates and repairs will appear here.",
            ["Notes de mise à jour"] = "Patch notes",
            ["Actualiser les notes"] = "Refresh notes",
            ["Actualiser les notes de mise à jour"] = "Refresh patch notes",
            ["Aucune note publiée"] = "No published notes",
            ["Les prochaines nouveautés apparaîtront ici."] = "Future updates will appear here.",
            ["Les changements publiés pour Atlas Launcher, regroupés par version."] = "Published Atlas Launcher changes, grouped by version.",
            ["Note de mise à jour Atlas Launcher"] = "Atlas Launcher patch note",
            ["NOTE DE MISE À JOUR"] = "PATCH NOTE",
            ["BROUILLON LOCAL"] = "LOCAL DRAFT",
            ["Non publiée"] = "Unpublished",
            ["Dernière version"] = "Latest version",
            ["Fermer la note de mise à jour"] = "Close patch note",
            ["Connexion"] = "Sign in",
            ["Inscription"] = "Create account",
            ["Nom d’utilisateur Atlas"] = "Atlas username",
            ["Nom d’utilisateur"] = "Username",
            ["Nom d’utilisateur pour l’inscription"] = "Username for registration",
            ["Mot de passe"] = "Password",
            ["Mot de passe pour l’inscription"] = "Password for registration",
            ["Confirmation du mot de passe"] = "Confirm password",
            ["NOM D’UTILISATEUR"] = "USERNAME",
            ["ADRESSE E-MAIL"] = "EMAIL ADDRESS",
            ["Adresse e-mail"] = "Email address",
            ["MOT DE PASSE"] = "PASSWORD",
            ["CONFIRMER LE MOT DE PASSE"] = "CONFIRM PASSWORD",
            ["3 à 20 lettres, chiffres ou underscores"] = "3 to 20 letters, numbers or underscores",
            ["10 à 128 caractères"] = "10 to 128 characters",
            ["MOT DE PASSE · 10 À 128 CARACTÈRES"] = "PASSWORD · 10 TO 128 CHARACTERS",
            ["Choix du formulaire d’authentification"] = "Authentication form selection",
            ["Se connecter"] = "Sign in",
            ["Créer mon compte"] = "Create my account",
            ["Connexion en cours"] = "Signing in",
            ["Connexion…"] = "Signing in…",
            ["Inscription…"] = "Creating account…",
            ["Afficher l’inscription"] = "Show registration",
            ["Afficher la connexion"] = "Show sign in",
            ["Fermer l’authentification"] = "Close authentication",
            ["Erreur d’authentification"] = "Authentication error",
            ["Adresse e-mail non vérifiée"] = "Email address not verified",
            ["Tu peux continuer, mais pense à confirmer ton adresse e-mail."] = "You can continue, but remember to verify your email address.",
            ["Profil"] = "Profile",
            ["Session Atlas active"] = "Atlas session active",
            ["Adresse e-mail vérifiée"] = "Email address verified",
            ["Gérer mon profil"] = "Manage my profile",
            ["Gérer mon compte"] = "Manage my account",
            ["Déconnexion"] = "Sign out",
            ["Déconnexion…"] = "Signing out…",
            ["Mon compte"] = "My account",
            ["Ton identité Atlas, ta sécurité et les appareils connectés."] = "Your Atlas identity, security and connected devices.",
            ["Mon profil"] = "My profile",
            ["Personnalise ton apparence et ton identité visible dans Atlas."] = "Customize your appearance and public identity in Atlas.",
            ["Identité"] = "Identity",
            ["Les informations utilisées dans Atlas Launcher."] = "Information used in Atlas Launcher.",
            ["Profil public"] = "Public profile",
            ["STATUT PERSONNEL"] = "PERSONAL STATUS",
            ["Statut personnel"] = "Personal status",
            ["Bio publique"] = "Public bio",
            ["Enregistrement…"] = "Saving…",
            ["Profil public enregistré."] = "Public profile saved.",
            ["Le statut ou la bio dépasse la longueur autorisée."] = "The status or bio exceeds the allowed length.",
            ["Sécurité"] = "Security",
            ["Sessions"] = "Sessions",
            ["COMPTE ATLAS"] = "ATLAS ACCOUNT",
            ["PHOTO DE PROFIL"] = "PROFILE PICTURE",
            ["Photo de profil Atlas"] = "Atlas profile picture",
            ["Profil synchronisé avec Atlas"] = "Profile synced with Atlas",
            ["Changer la photo"] = "Change picture",
            ["Changer la photo de profil"] = "Change profile picture",
            ["Supprimer"] = "Remove",
            ["Supprimer la photo"] = "Remove picture",
            ["Supprimer la photo de profil"] = "Remove profile picture",
            ["Supprimer ta photo de profil ?"] = "Remove your profile picture?",
            ["Ton initiale sera utilisée à la place."] = "Your initial will be used instead.",
            ["Modifier"] = "Edit",
            ["Modifier l’adresse e-mail"] = "Change email address",
            ["Modifier le mot de passe"] = "Change password",
            ["NOUVELLE ADRESSE E-MAIL"] = "NEW EMAIL ADDRESS",
            ["La nouvelle adresse devra être validée."] = "The new address will need to be verified.",
            ["MOT DE PASSE ACTUEL"] = "CURRENT PASSWORD",
            ["NOUVEAU MOT DE PASSE"] = "NEW PASSWORD",
            ["CONFIRMER LE NOUVEAU MOT DE PASSE"] = "CONFIRM NEW PASSWORD",
            ["Enregistrer"] = "Save",
            ["Modification en cours…"] = "Saving changes…",
            ["Le nouveau mot de passe doit contenir entre 10 et 128 caractères."] = "The new password must contain between 10 and 128 characters.",
            ["Vérifiée"] = "Verified",
            ["(Vérifiée)"] = "(Verified)",
            ["(Non vérifiée)"] = "(Not verified)",
            ["Ton adresse e-mail est vérifiée."] = "Your email address is verified.",
            ["Voir la sécurité"] = "View security",
            ["Renvoyer la validation"] = "Resend verification",
            ["Double authentification"] = "Two-factor authentication",
            ["Cette protection n’est pas encore disponible côté Atlas."] = "This protection is not yet available in Atlas.",
            ["À venir"] = "Coming soon",
            ["Bientôt disponible"] = "Coming soon",
            ["Compte protégé"] = "Account protected",
            ["Appareils connectés"] = "Connected devices",
            ["Cet appareil"] = "This device",
            ["Déconnecter"] = "Disconnect",
            ["Déconnecter les autres"] = "Disconnect others",
            ["Windows · Atlas Launcher"] = "Windows · Atlas Launcher",
            ["Liège, Belgique · active maintenant"] = "Liège, Belgium · active now",
            ["Namur, Belgique · il y a 2 jours"] = "Namur, Belgium · 2 days ago",
            ["Recadrer la photo"] = "Crop picture",
            ["Position et cadrage"] = "Position and crop",
            ["Aperçus"] = "Previews",
            ["Format préparé"] = "Prepared format",
            ["Image carrée · affichage circulaire · haute définition"] = "Square image · circular display · high definition",
            ["Utiliser la photo"] = "Use picture",
            ["Fermer le recadrage"] = "Close crop editor",
            ["Mes amis"] = "My friends",
            ["AMIS ATLAS"] = "ATLAS FRIENDS",
            ["Ajouter un ami"] = "Add friend",
            ["Pseudo Atlas"] = "Atlas username",
            ["Envoyer la demande"] = "Send request",
            ["Envoyer la demande d’ami"] = "Send friend request",
            ["Actualiser"] = "Refresh",
            ["Actualiser les amis"] = "Refresh friends",
            ["DEMANDES REÇUES"] = "RECEIVED REQUESTS",
            ["DEMANDES ENVOYÉES"] = "SENT REQUESTS",
            ["Demande reçue"] = "Request received",
            ["Accepter"] = "Accept",
            ["Accepter la demande"] = "Accept request",
            ["Refuser"] = "Decline",
            ["Refuser la demande"] = "Decline request",
            ["Retirer de mes amis"] = "Remove friend",
            ["Retirer cet ami ?"] = "Remove this friend?",
            ["Cette personne sera retirée de ta liste d’amis."] = "This person will be removed from your friends list.",
            ["Retirer"] = "Remove",
            ["Déconnexion groupée · À venir"] = "Sign out all other devices · Coming soon",
            ["Glisser pour déplacer · Molette pour zoomer"] = "Drag to move · Scroll to zoom",
            ["Mise à jour"] = "Update",
            ["Actions"] = "Actions",
            ["Actions pour cet ami"] = "Actions for this friend",
            ["Voir le profil"] = "View profile",
            ["Retour à la liste"] = "Back to list",
            ["Retour à la liste d’amis"] = "Back to friends list",
            ["PERSONNAGE ACTIF"] = "ACTIVE CHARACTER",
            ["PERSONNAGES"] = "CHARACTERS",
            ["Aucun statut renseigné."] = "No status provided.",
            ["Aucune bio renseignée."] = "No bio provided.",
            ["Disponible pour jouer"] = "Available to play",
            ["Couronne de glace"] = "Icecrown",
            ["EN JEU"] = "IN GAME",
            ["HORS LIGNE"] = "OFFLINE",
            [" en jeu sur "] = " playing in ",
            ["Aucun ami pour le moment"] = "No friends yet",
            ["Addons Atlas"] = "Atlas addons",
            ["BIBLIOTHÈQUE ATLAS"] = "ATLAS LIBRARY",
            ["WOTLK CLASSIC"] = "WOTLK CLASSIC",
            ["VERSION ET ÉTAT"] = "VERSION AND STATUS",
            ["Rechercher un addon"] = "Search for an addon",
            ["Personnalise ton expérience WotLK Classic."] = "Customize your WotLK Classic experience.",
            ["VERSION"] = "VERSION",
            ["COMPATIBILITÉ"] = "COMPATIBILITY",
            ["FICHIERS GÉRÉS"] = "MANAGED FILES",
            ["ACTION"] = "ACTION",
            ["ADDON"] = "ADDON",
            ["Supprimer Questie ?"] = "Remove Questie?",
            ["Seuls les fichiers gérés par Atlas seront supprimés."] = "Only files managed by Atlas will be removed.",
            ["Le jeu est ouvert : utilise /reload après le changement."] = "The game is running: use /reload after the change.",
            ["Le jeu est ouvert. Les changements restent disponibles et seront pris en compte après /reload."] = "The game is running. Changes remain available and will apply after /reload.",
            ["Personnalise Atlas Launcher et ton client WotLK Classic."] = "Customize Atlas Launcher and your WotLK Classic client.",
            ["CATÉGORIES"] = "CATEGORIES",
            ["Préférences du launcher"] = "Launcher preferences",
            ["Événements"] = "Events",
            ["Langue de l’interface"] = "Interface language",
            ["Français"] = "Français",
            ["English"] = "English",
            ["Démarrer avec Windows"] = "Start with Windows",
            ["Réduire dans la zone de notification à la fermeture d’Atlas Launcher"] = "Minimize to the notification area when closing Atlas Launcher",
            ["Installation du jeu"] = "Game installation",
            ["DOSSIER DU CLIENT"] = "CLIENT FOLDER",
            ["Configuration du jeu"] = "Game configuration",
            ["Langue du jeu"] = "Game language",
            ["Texte de quête instantané"] = "Instant quest text",
            ["Disponibilité des mises à jour Atlas."] = "Atlas update availability.",
            ["Atlas Launcher"] = "Atlas Launcher",
            ["ATLAS LAUNCHER"] = "ATLAS LAUNCHER",
            ["VERSION INSTALLÉE"] = "INSTALLED VERSION",
            ["VERSION DISPONIBLE"] = "AVAILABLE VERSION",
            ["Rechercher les mises à jour"] = "Check for updates",
            ["Connexions des amis"] = "Friend connections",
            ["Nouvelles demandes d’amis"] = "New friend requests",
            ["Toujours activées"] = "Always enabled",
            ["Journaux locaux"] = "Local logs",
            ["Ouvrir les journaux"] = "Open logs",
            ["Rapport de diagnostic"] = "Diagnostic report",
            ["Copier le rapport"] = "Copy report",
            ["Dossier du launcher"] = "Launcher folder",
            ["Outils"] = "Tools",
            ["État et versions"] = "Status and versions",
            ["État local"] = "Local status",
            ["État des services"] = "Service status",
            ["Client WotLK Classic"] = "WotLK Classic client",
            ["Atlas Launcher · portable"] = "Atlas Launcher · portable",
            ["Preview fictive"] = "Mock preview",
            ["Notification locale"] = "Local notification",
            ["Ami connecté"] = "Friend online",
            ["Nouvelle demande d’ami"] = "New friend request",
            ["est maintenant en ligne."] = "is now online.",
            ["souhaite t’ajouter à ses amis."] = "would like to add you as a friend.",
            ["Plusieurs amis viennent de se connecter."] = "Several friends just came online.",
            ["Plusieurs nouvelles demandes d’amis sont arrivées."] = "Several new friend requests have arrived.",
            ["À jour"] = "Up to date",
            ["À réparer"] = "Repair needed",
            ["Non installé"] = "Not installed",
            ["Non vérifié"] = "Not verified",
            ["Non vérifiée"] = "Not checked",
            ["Jamais"] = "Never",
            ["Disponible"] = "Available",
            ["Aucune"] = "None",
            ["Recherche en cours"] = "Checking for updates",
            ["Mise à jour en cours"] = "Update in progress",
            ["Réparation en cours"] = "Repair in progress",
            ["Analyse du client local…"] = "Scanning local client…",
            ["Analyse des fichiers locaux…"] = "Scanning local files…",
            ["Analyse des fichiers nécessaires"] = "Scanning required files",
            ["Analyse complète du client"] = "Full client scan",
            ["Analyse en arrière-plan"] = "Background scan",
            ["Analyse terminée"] = "Scan complete",
            ["Comparaison des fichiers…"] = "Comparing files…",
            ["Chargement du manifeste…"] = "Loading manifest…",
            ["Manifeste reçu"] = "Manifest received",
            ["Préparation du client"] = "Preparing client",
            ["Préparation des fichiers"] = "Preparing files",
            ["Préparation du redémarrage"] = "Preparing restart",
            ["Préparation du redémarrage…"] = "Preparing restart…",
            ["Préparation de l’opération…"] = "Preparing operation…",
            ["Préparation…"] = "Preparing…",
            ["Téléchargement du client"] = "Downloading client",
            ["Téléchargement de la réparation"] = "Downloading repair",
            ["Téléchargement des fichiers manquants"] = "Downloading missing files",
            ["Téléchargement des fichiers à réparer"] = "Downloading files to repair",
            ["Téléchargement des fichiers du client"] = "Downloading client files",
            ["Téléchargement de l’addon"] = "Downloading addon",
            ["Téléchargement d’Atlas Launcher…"] = "Downloading Atlas Launcher…",
            ["Téléchargement de la nouvelle version…"] = "Downloading new version…",
            ["Téléchargement annulé"] = "Download cancelled",
            ["Application de la mise à jour"] = "Applying update",
            ["Application de la réparation"] = "Applying repair",
            ["Application des fichiers réparés"] = "Applying repaired files",
            ["Application des fichiers réparés…"] = "Applying repaired files…",
            ["Écriture des fichiers du client"] = "Writing client files",
            ["Enregistrement de l’installation"] = "Saving installation",
            ["Nettoyage des anciens fichiers…"] = "Cleaning old files…",
            ["Nettoyage terminé"] = "Cleanup complete",
            ["Finalisation de l’installation…"] = "Finishing installation…",
            ["Finalisation…"] = "Finishing…",
            ["Redémarrage en cours"] = "Restarting",
            ["Arrêt de l’opération en cours…"] = "Stopping current operation…",
            ["Opération en cours"] = "Operation in progress",
            ["Opération interrompue"] = "Operation interrupted",
            ["Opération annulée"] = "Operation cancelled",
            ["Opération annulée."] = "Operation cancelled.",
            ["Installation terminée"] = "Installation complete",
            ["Mise à jour terminée"] = "Update complete",
            ["Vérification terminée"] = "Verification complete",
            ["Réparation terminée"] = "Repair complete",
            ["Installation échouée"] = "Installation failed",
            ["Mise à jour échouée"] = "Update failed",
            ["Vérification échouée"] = "Verification failed",
            ["Réparation échouée"] = "Repair failed",
            ["Suppression échouée"] = "Removal failed",
            ["Vérification annulée"] = "Verification cancelled",
            ["Réparation annulée"] = "Repair cancelled",
            ["Suppression annulée"] = "Removal cancelled",
            ["Terminé"] = "Complete",
            ["Installé"] = "Installed",
            ["Mis à jour"] = "Updated",
            ["Réparé"] = "Repaired",
            ["Supprimé"] = "Removed",
            ["Réparer"] = "Repair",
            ["Installation…"] = "Installing…",
            ["Mise à jour…"] = "Updating…",
            ["Réparation…"] = "Repairing…",
            ["Suppression…"] = "Removing…",
            ["Progression indéterminée"] = "Progress unavailable",
            ["Cette action attend la fin de l’opération en cours."] = "This action is waiting for the current operation to finish.",
            ["Une autre opération Atlas est déjà en cours."] = "Another Atlas operation is already in progress.",
            ["Une autre opération est déjà en cours."] = "Another operation is already in progress.",
            ["L’opération n’a pas pu être terminée."] = "The operation could not be completed.",
            ["L’opération n’a pas pu être terminée. Consulte le diagnostic."] = "The operation could not be completed. Check diagnostics.",
            ["Le téléchargement n’a pas pu être terminé."] = "The download could not be completed.",
            ["Le téléchargement n’a pas pu être terminé. Tu peux réessayer ou ouvrir le diagnostic."] = "The download could not be completed. Try again or open diagnostics.",
            ["Le téléchargement a pris trop de temps. Réessaie."] = "The download took too long. Try again.",
            ["Atlas n’a pas accès au dossier du jeu."] = "Atlas cannot access the game folder.",
            ["Autorisation requise"] = "Permission required",
            ["Tu peux jouer pendant l’analyse"] = "You can play during the scan",
            ["En arrière-plan"] = "In the background",
            ["Actualisation…"] = "Refreshing…",
            ["Actualisation des amis…"] = "Refreshing friends…",
            ["Actualisation du profil…"] = "Refreshing profile…",
            ["Restauration de la session…"] = "Restoring session…",
            ["Déconnexion en cours."] = "Signing out.",
            ["Demande d’ami envoyée."] = "Friend request sent.",
            ["Demande d’ami acceptée."] = "Friend request accepted.",
            ["Demande refusée."] = "Request declined.",
            ["Demande envoyée annulée."] = "Sent request cancelled.",
            ["Ami retiré de ta liste."] = "Friend removed from your list.",
            ["Envoi de la demande…"] = "Sending request…",
            ["Acceptation de la demande…"] = "Accepting request…",
            ["Refus de la demande…"] = "Declining request…",
            ["Annulation de la demande…"] = "Cancelling request…",
            ["Annulation…"] = "Cancelling…",
            ["Retrait de l’ami…"] = "Removing friend…",
            ["Annuler l’envoi"] = "Cancel request",
            ["Une demande est déjà en attente."] = "A request is already pending.",
            ["Ce compte fait déjà partie de tes amis."] = "This account is already in your friends list.",
            ["Tu ne peux pas t’ajouter toi-même."] = "You cannot add yourself.",
            ["Cette demande n’est plus disponible."] = "This request is no longer available.",
            ["Reconnecte-toi pour gérer tes amis."] = "Sign in again to manage your friends.",
            ["Saisis un nom d’utilisateur Atlas valide."] = "Enter a valid Atlas username.",
            ["Chargement du catalogue…"] = "Loading catalog…",
            ["Le catalogue Atlas n’est pas encore disponible."] = "The Atlas catalog is not available yet.",
            ["Le catalogue Atlas n’a pas pu être chargé."] = "The Atlas catalog could not be loaded.",
            ["Le catalogue Atlas n’a pas pu être actualisé. Les informations affichées sont conservées localement."] = "The Atlas catalog could not be refreshed. Displayed information was kept locally.",
            ["Atlas récupère les informations disponibles."] = "Atlas is retrieving available information.",
            ["Aucun addon ne correspond à ce filtre."] = "No addon matches this filter.",
            ["Modifie la recherche ou le filtre sélectionné."] = "Change the search or selected filter.",
            ["Tout mettre à jour"] = "Update all",
            ["Tous les addons disponibles ont été mis à jour."] = "All available addons have been updated.",
            ["Installation externe détectée"] = "External installation detected",
            ["Aucune version installée"] = "No version installed",
            ["Aucun dossier déclaré"] = "No folder declared",
            ["Aucune dépendance requise"] = "No dependencies required",
            ["Détecté (non géré)"] = "Detected (unmanaged)",
            ["Reconnecte-toi pour gérer tes addons."] = "Sign in again to manage your addons.",
            ["Installe d’abord le client WotLK pour gérer ses addons."] = "Install the WotLK client first to manage its addons.",
            ["Installe d’abord le client WotLK."] = "Install the WotLK client first.",
            ["Cet addon n’est plus présent dans le catalogue."] = "This addon is no longer in the catalog.",
            ["Impossible de télécharger cet addon pour le moment."] = "This addon cannot be downloaded right now.",
            ["Atlas n’a pas pu écrire les fichiers de cet addon."] = "Atlas could not write this addon's files.",
            ["Certains fichiers de l’addon sont utilisés par une autre application."] = "Some addon files are being used by another application.",
            ["Addon installé."] = "Addon installed.",
            ["Addon mis à jour."] = "Addon updated.",
            ["Addon réparé."] = "Addon repaired.",
            ["Addon supprimé."] = "Addon removed.",
            ["Photo de profil actualisée."] = "Profile picture updated.",
            ["Préparation de la photo…"] = "Preparing picture…",
            ["Envoi de la photo…"] = "Uploading picture…",
            ["Traitement par Atlas…"] = "Processing with Atlas…",
            ["Suppression de la photo en cours…"] = "Removing picture…",
            ["Cette image ne peut pas être utilisée."] = "This image cannot be used.",
            ["L’image dépasse la limite de 25 Mo."] = "The image exceeds the 25 MB limit.",
            ["Le recadrage de cette image n’est pas valide."] = "This image crop is invalid.",
            ["Une modification de photo est déjà en cours."] = "A picture change is already in progress.",
            ["Atlas n’a pas pu traiter cette photo."] = "Atlas could not process this picture.",
            ["La photo n’a pas pu être modifiée. Réessaie."] = "The picture could not be changed. Try again.",
            ["L’état de la photo n’a pas pu être confirmé. Actualise le profil."] = "The picture status could not be confirmed. Refresh the profile.",
            ["Termine l’opération en cours avant de modifier ta photo."] = "Finish the current operation before changing your picture.",
            ["Sélectionne de nouveau la photo avant de l’utiliser."] = "Select the picture again before using it.",
            ["Le fichier sélectionné n’est plus disponible."] = "The selected file is no longer available.",
            ["La photo n’a pas pu être préparée. Réessaie avec une autre image."] = "The picture could not be prepared. Try another image.",
            ["Cette adresse e-mail est déjà utilisée."] = "This email address is already in use.",
            ["Ta session Atlas a expiré. Reconnecte-toi."] = "Your Atlas session has expired. Sign in again.",
            ["Ta session Atlas doit être renouvelée."] = "Your Atlas session needs to be renewed.",
            ["Cette session n’est plus active."] = "This session is no longer active.",
            ["Trop de tentatives. Réessaie dans quelques instants."] = "Too many attempts. Try again shortly.",
            ["Atlas met trop de temps à répondre. Réessaie."] = "Atlas is taking too long to respond. Try again.",
            ["Atlas n’a pas pu appliquer cette modification."] = "Atlas could not apply this change.",
            ["Cette modification n’a pas pu être appliquée. Réessaie."] = "This change could not be applied. Try again.",
            ["Adresse e-mail modifiée. Un message de validation a été envoyé."] = "Email address changed. A verification message was sent.",
            ["Adresse e-mail modifiée. Le message de validation n’a pas pu être envoyé."] = "Email address changed. The verification message could not be sent.",
            ["Un message de validation a été envoyé."] = "A verification message was sent.",
            ["Mot de passe modifié."] = "Password changed.",
            ["Appareil déconnecté."] = "Device disconnected.",
            ["Termine l’opération en cours avant de modifier ton compte."] = "Finish the current operation before changing your account.",
            ["La session locale a été fermée, mais la déconnexion n’a pas pu être confirmée."] = "The local session was closed, but sign-out could not be confirmed.",
            ["La déconnexion a expiré. Réessaie dans quelques instants."] = "Sign-out timed out. Try again shortly.",
            ["Atlas a refusé la déconnexion. Ta session reste active."] = "Atlas rejected sign-out. Your session remains active.",
            ["La session locale n’a pas pu être supprimée."] = "The local session could not be removed.",
            ["La déconnexion n’a pas pu être terminée. Réessaie."] = "Sign-out could not be completed. Try again.",
            ["Le démarrage avec Windows n’a pas pu être modifié."] = "Start with Windows could not be changed.",
            ["La préférence n’a pas pu être enregistrée. La valeur précédente est conservée."] = "The preference could not be saved. The previous value was kept.",
            ["Préférence enregistrée sur cet ordinateur."] = "Preference saved on this computer.",
            ["Modifications non enregistrées"] = "Unsaved changes",
            ["Les changements de cette catégorie n’ont pas encore été appliqués."] = "Changes in this category have not been applied yet."
        };

    private static readonly IReadOnlyDictionary<string, string> FrenchByEnglish =
        EnglishByFrench
            .GroupBy(pair => pair.Value, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.First().Key, StringComparer.Ordinal);

    private static readonly (string French, string English)[] EnglishFragments =
    [
        ("Dernière actualisation réussie à ", "Last successful refresh at "),
        ("Données précédentes conservées · actualisation indisponible.", "Previous data retained · refresh unavailable."),
        (" Atlas · actualisation indisponible", " Atlas · refresh unavailable"),
        ("Hors ligne · vu hier à ", "Offline · seen yesterday at "),
        ("Hors ligne · vu le ", "Offline · seen on "),
        ("Aujourd’hui à ", "Today at "),
        ("Hier à ", "Yesterday at "),
        ("Vu le ", "Seen on "),
        ("En jeu · ", "In game · "),
        ("Dernière activité le ", "Last active on "),
        ("Créée le ", "Created on "),
        (" · niveau ", " · level "),
        (" niveau ", " level "),
        (" appareils connectés", " connected devices"),
        (" appareil connecté", " connected device"),
        (" fichiers analysés", " files scanned"),
        (" fichier analysé", " file scanned"),
        (" dossiers gérés", " managed folders"),
        (" dossier géré · ", " managed folder · "),
        ("Version installée  ", "Installed version  "),
        ("Version disponible  ", "Available version  "),
        ("Mise à jour disponible · ", "Update available · "),
        ("Dépendances · ", "Dependencies · "),
        ("Installés  ", "Installed  "),
        ("Tous  ", "All  "),
        ("Mises à jour  ", "Updates  "),
        ("Aucun addon trouvé pour “", "No addon found for “"),
        ("Installation de ", "Installing "),
        ("Mise à jour de ", "Updating "),
        ("Réparation de ", "Repairing "),
        ("Suppression de ", "Removing "),
        ("Envoi de la photo… ", "Uploading picture… "),
        ("Envoi… ", "Uploading… "),
        (" s restantes", " s remaining"),
        (" min restantes", " min remaining"),
        ("quelques secondes", "a few seconds"),
        ("environ ", "about "),
        (" · données conservées", " · data retained"),
        (" Utilise /reload dans le jeu pour l’activer.", " Use /reload in game to enable it."),
        (" en jeu sur ", " playing in "),
        (" amis · ", " friends · "),
        (" ami · ", " friend · "),
        (" en jeu", " in game"),
        (" en ligne", " online")
    ];

    private static string _currentLocale = FrenchLocale;

    internal static event EventHandler? LocaleChanged;

    internal static string CurrentLocale => Volatile.Read(ref _currentLocale);

    internal static bool IsEnglish => string.Equals(
        CurrentLocale,
        EnglishLocale,
        StringComparison.OrdinalIgnoreCase);

    internal static void SetLocale(string? locale)
    {
        string normalized = LauncherSettings.NormalizeInterfaceLocale(locale);
        bool changed = !string.Equals(
            CurrentLocale,
            normalized,
            StringComparison.OrdinalIgnoreCase);
        CultureInfo culture = CultureInfo.GetCultureInfo(normalized);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        Volatile.Write(ref _currentLocale, normalized);
        if (changed)
        {
            LocaleChanged?.Invoke(null, EventArgs.Empty);
        }
    }

    internal static string Text(string? source)
    {
        if (string.IsNullOrEmpty(source))
        {
            return source ?? string.Empty;
        }

        IReadOnlyDictionary<string, string> catalog = IsEnglish
            ? EnglishByFrench
            : FrenchByEnglish;
        return catalog.TryGetValue(source, out string? translated)
            ? translated
            : source;
    }

    internal static string TranslateFromFrench(string source)
    {
        ArgumentNullException.ThrowIfNull(source);
        if (EnglishByFrench.TryGetValue(source, out string? exact))
        {
            return exact;
        }

        string translated = source;
        foreach ((string french, string english) in EnglishFragments)
        {
            translated = translated.Replace(french, english, StringComparison.Ordinal);
        }

        if (translated.StartsWith("Last active on ", StringComparison.Ordinal)
            || translated.StartsWith("Seen on ", StringComparison.Ordinal)
            || translated.StartsWith("Offline · seen on ", StringComparison.Ordinal))
        {
            translated = translated.Replace(" à ", " at ", StringComparison.Ordinal);
        }

        return translated;
    }

    internal static string Format(string frenchFormat, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Text(frenchFormat), arguments);
}
