using System.Globalization;

namespace WotLK.Launcher.UI.V2.Localization;

internal static class LauncherLocalization
{
    internal const string FrenchLocale = "fr-FR";
    internal const string EnglishLocale = "en-US";

    private static readonly IReadOnlyDictionary<string, string> EnglishByFrench =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Jeu"] = "Game",
            ["Mises à jour"] = "Updates",
            ["Notes"] = "Notes",
            ["Addons"] = "Addons",
            ["ADDONS"] = "ADDONS",
            ["Amis"] = "Friends",
            ["AMIS"] = "FRIENDS",
            ["Paramètres"] = "Settings",
            ["Général"] = "General",
            ["Notifications"] = "Notifications",
            ["Diagnostic"] = "Diagnostics",
            ["Aide et diagnostic"] = "Help and diagnostics",
            ["Réduire"] = "Minimize",
            ["Agrandir ou restaurer"] = "Maximize or restore",
            ["Réduire dans la zone de notification"] = "Minimize to the notification area",
            ["Ouvrir Atlas Launcher"] = "Open Atlas Launcher",
            ["Quitter"] = "Quit",
            ["Ouvrir"] = "Open",
            ["Version locale de test"] = "Local test version",
            ["Atlas Launcher · Prévisualisation V2"] = "Atlas Launcher · V2 Preview",
            ["LOCAL"] = "LOCAL",
            ["Arthas en ligne"] = "Arthas online",
            ["Arthas dégradé"] = "Arthas degraded",
            ["Arthas hors ligne"] = "Arthas offline",
            ["Serveur de jeu en ligne"] = "Game server online",
            ["Services de jeu dégradés"] = "Game services degraded",
            ["Serveur de jeu hors ligne"] = "Game server offline",
            ["Vérification du serveur de jeu…"] = "Checking game server…",
            ["État du serveur de jeu indisponible"] = "Game server status unavailable",
            ["Serveur de jeu non vérifié"] = "Game server not checked",
            ["En ligne"] = "Online",
            ["Hors ligne"] = "Offline",
            ["Indisponible"] = "Unavailable",
            ["Chargement…"] = "Loading…",
            ["Activité"] = "Activity",
            ["Ouvrir le centre d’activité"] = "Open activity center",
            ["Ouvrir le panneau Amis"] = "Open Friends panel",
            ["Fermer le centre d’activité"] = "Close activity center",
            ["Fermer le panneau Amis"] = "Close Friends panel",
            ["Fermer le profil"] = "Close profile",
            ["Fermer"] = "Close",
            ["Bienvenue en Norfendre"] = "Welcome to Northrend",
            ["Votre aventure vous attend"] = "Your adventure awaits",
            ["ROYAUME ARTHAS"] = "ARTHAS REALM",
            ["Jouer"] = "Play",
            ["En cours de lancement"] = "Launching game",
            ["Jeu en cours de lancement"] = "Launching game",
            ["Jeu en cours d’utilisation"] = "Game running",
            ["Installation"] = "Install",
            ["Installer"] = "Install",
            ["Mettre à jour"] = "Update",
            ["Réessayer"] = "Try again",
            ["Vérifier"] = "Verify",
            ["Vérifier et réparer"] = "Verify and repair",
            ["Ouvrir le dossier"] = "Open folder",
            ["Parcourir"] = "Browse",
            ["Client non installé"] = "Client not installed",
            ["Client prêt"] = "Client ready",
            ["Client prêt · non vérifié"] = "Client ready · not verified",
            ["Client prêt · à jour"] = "Client ready · up to date",
            ["Client prêt · mise à jour disponible"] = "Client ready · update available",
            ["Mise à jour disponible"] = "Update available",
            ["Vérification en cours"] = "Verification in progress",
            ["Vérification en cours…"] = "Verification in progress…",
            ["Téléchargement en cours"] = "Downloading",
            ["Installation en cours"] = "Installing",
            ["Annuler"] = "Cancel",
            ["Annuler l’opération"] = "Cancel operation",
            ["Ouvrir l’élément associé"] = "Open related item",
            ["OPÉRATIONS EN COURS"] = "CURRENT OPERATIONS",
            ["RÉCENT"] = "RECENT",
            ["EN COURS"] = "IN PROGRESS",
            ["EN ATTENTE"] = "PENDING",
            ["En attente"] = "Pending",
            ["Aucune activité récente"] = "No recent activity",
            ["Les installations, mises à jour et réparations apparaîtront ici."] = "Installations, updates and repairs will appear here.",
            ["Notes de mise à jour"] = "Patch notes",
            ["Actualiser les notes"] = "Refresh notes",
            ["Actualiser les notes de mise à jour"] = "Refresh patch notes",
            ["Aucune note publiée"] = "No published notes",
            ["Les prochaines nouveautés apparaîtront ici."] = "Future updates will appear here.",
            ["Les changements publiés pour Atlas Launcher, regroupés par version."] = "Published Atlas Launcher changes, grouped by version.",
            ["Note de mise à jour Atlas Launcher"] = "Atlas Launcher patch note",
            ["NOTE DE MISE À JOUR"] = "PATCH NOTE",
            ["BROUILLON LOCAL"] = "LOCAL DRAFT",
            ["Non publiée"] = "Unpublished",
            ["Dernière version"] = "Latest version",
            ["Fermer la note de mise à jour"] = "Close patch note",
            ["Connexion"] = "Sign in",
            ["Inscription"] = "Create account",
            ["Nom d’utilisateur Atlas"] = "Atlas username",
            ["Nom d’utilisateur"] = "Username",
            ["Nom d’utilisateur pour l’inscription"] = "Username for registration",
            ["Mot de passe"] = "Password",
            ["Mot de passe pour l’inscription"] = "Password for registration",
            ["Confirmation du mot de passe"] = "Confirm password",
            ["NOM D’UTILISATEUR"] = "USERNAME",
            ["ADRESSE E-MAIL"] = "EMAIL ADDRESS",
            ["Adresse e-mail"] = "Email address",
            ["MOT DE PASSE"] = "PASSWORD",
            ["CONFIRMER LE MOT DE PASSE"] = "CONFIRM PASSWORD",
            ["3 à 20 lettres, chiffres ou underscores"] = "3 to 20 letters, numbers or underscores",
            ["10 à 128 caractères"] = "10 to 128 characters",
            ["MOT DE PASSE · 10 À 128 CARACTÈRES"] = "PASSWORD · 10 TO 128 CHARACTERS",
            ["Choix du formulaire d’authentification"] = "Authentication form selection",
            ["Se connecter"] = "Sign in",
            ["Créer mon compte"] = "Create my account",
            ["Connexion en cours"] = "Signing in",
            ["Connexion…"] = "Signing in…",
            ["Inscription…"] = "Creating account…",
            ["Afficher l’inscription"] = "Show registration",
            ["Afficher la connexion"] = "Show sign in",
            ["Fermer l’authentification"] = "Close authentication",
            ["Erreur d’authentification"] = "Authentication error",
            ["Adresse e-mail non vérifiée"] = "Email address not verified",
            ["Tu peux continuer, mais pense à confirmer ton adresse e-mail."] = "You can continue, but remember to verify your email address.",
            ["Profil"] = "Profile",
            ["Session Atlas active"] = "Atlas session active",
            ["Adresse e-mail vérifiée"] = "Email address verified",
            ["Gérer mon profil"] = "Manage my profile",
            ["Gérer mon compte"] = "Manage my account",
            ["Déconnexion"] = "Sign out",
            ["Déconnexion…"] = "Signing out…",
            ["Mon compte"] = "My account",
            ["Ton identité Atlas, ta sécurité et les appareils connectés."] = "Your Atlas identity, security and connected devices.",
            ["Identité"] = "Identity",
            ["Les informations utilisées dans Atlas Launcher."] = "Information used in Atlas Launcher.",
            ["Sécurité"] = "Security",
            ["Sessions"] = "Sessions",
            ["COMPTE ATLAS"] = "ATLAS ACCOUNT",
            ["PHOTO DE PROFIL"] = "PROFILE PICTURE",
            ["Photo de profil Atlas"] = "Atlas profile picture",
            ["Profil synchronisé avec Atlas"] = "Profile synced with Atlas",
            ["Changer la photo"] = "Change picture",
            ["Changer la photo de profil"] = "Change profile picture",
            ["Supprimer"] = "Remove",
            ["Supprimer la photo"] = "Remove picture",
            ["Supprimer la photo de profil"] = "Remove profile picture",
            ["Supprimer ta photo de profil ?"] = "Remove your profile picture?",
            ["Ton initiale sera utilisée à la place."] = "Your initial will be used instead.",
            ["Modifier"] = "Edit",
            ["Modifier l’adresse e-mail"] = "Change email address",
            ["Modifier le mot de passe"] = "Change password",
            ["NOUVELLE ADRESSE E-MAIL"] = "NEW EMAIL ADDRESS",
            ["La nouvelle adresse devra être validée."] = "The new address will need to be verified.",
            ["MOT DE PASSE ACTUEL"] = "CURRENT PASSWORD",
            ["NOUVEAU MOT DE PASSE"] = "NEW PASSWORD",
            ["CONFIRMER LE NOUVEAU MOT DE PASSE"] = "CONFIRM NEW PASSWORD",
            ["Enregistrer"] = "Save",
            ["Modification en cours…"] = "Saving changes…",
            ["Le nouveau mot de passe doit contenir entre 10 et 128 caractères."] = "The new password must contain between 10 and 128 characters.",
            ["Vérifiée"] = "Verified",
            ["Ton adresse e-mail est vérifiée."] = "Your email address is verified.",
            ["Voir la sécurité"] = "View security",
            ["Renvoyer la validation"] = "Resend verification",
            ["Double authentification"] = "Two-factor authentication",
            ["Cette protection n’est pas encore disponible côté Atlas."] = "This protection is not yet available in Atlas.",
            ["À venir"] = "Coming soon",
            ["Bientôt disponible"] = "Coming soon",
            ["Compte protégé"] = "Account protected",
            ["Appareils connectés"] = "Connected devices",
            ["Cet appareil"] = "This device",
            ["Déconnecter"] = "Disconnect",
            ["Déconnecter les autres"] = "Disconnect others",
            ["Windows · Atlas Launcher"] = "Windows · Atlas Launcher",
            ["Liège, Belgique · active maintenant"] = "Liège, Belgium · active now",
            ["Namur, Belgique · il y a 2 jours"] = "Namur, Belgium · 2 days ago",
            ["Recadrer la photo"] = "Crop picture",
            ["Position et cadrage"] = "Position and crop",
            ["Aperçus"] = "Previews",
            ["Format préparé"] = "Prepared format",
            ["Image carrée · affichage circulaire · haute définition"] = "Square image · circular display · high definition",
            ["Utiliser la photo"] = "Use picture",
            ["Fermer le recadrage"] = "Close crop editor",
            ["Mes amis"] = "My friends",
            ["AMIS ATLAS"] = "ATLAS FRIENDS",
            ["Ajouter un ami"] = "Add friend",
            ["Envoyer la demande"] = "Send request",
            ["Envoyer la demande d’ami"] = "Send friend request",
            ["Actualiser"] = "Refresh",
            ["Actualiser les amis"] = "Refresh friends",
            ["DEMANDES REÇUES"] = "RECEIVED REQUESTS",
            ["DEMANDES ENVOYÉES"] = "SENT REQUESTS",
            ["Demande reçue"] = "Request received",
            ["Accepter"] = "Accept",
            ["Accepter la demande"] = "Accept request",
            ["Refuser"] = "Decline",
            ["Refuser la demande"] = "Decline request",
            ["Retirer de mes amis"] = "Remove friend",
            [" en jeu sur "] = " playing in ",
            ["Aucun ami pour le moment"] = "No friends yet",
            ["Addons Atlas"] = "Atlas addons",
            ["BIBLIOTHÈQUE ATLAS"] = "ATLAS LIBRARY",
            ["WOTLK CLASSIC"] = "WOTLK CLASSIC",
            ["VERSION ET ÉTAT"] = "VERSION AND STATUS",
            ["Rechercher un addon"] = "Search for an addon",
            ["Personnalise ton expérience WotLK Classic."] = "Customize your WotLK Classic experience.",
            ["VERSION"] = "VERSION",
            ["COMPATIBILITÉ"] = "COMPATIBILITY",
            ["FICHIERS GÉRÉS"] = "MANAGED FILES",
            ["ACTION"] = "ACTION",
            ["ADDON"] = "ADDON",
            ["Supprimer Questie ?"] = "Remove Questie?",
            ["Seuls les fichiers gérés par Atlas seront supprimés."] = "Only files managed by Atlas will be removed.",
            ["Le jeu est ouvert : utilise /reload après le changement."] = "The game is running: use /reload after the change.",
            ["Le jeu est ouvert. Les changements restent disponibles et seront pris en compte après /reload."] = "The game is running. Changes remain available and will apply after /reload.",
            ["Personnalise Atlas Launcher et ton client WotLK Classic."] = "Customize Atlas Launcher and your WotLK Classic client.",
            ["CATÉGORIES"] = "CATEGORIES",
            ["Préférences du launcher"] = "Launcher preferences",
            ["Événements"] = "Events",
            ["Langue de l’interface"] = "Interface language",
            ["Français"] = "Français",
            ["English"] = "English",
            ["Démarrer avec Windows"] = "Start with Windows",
            ["Réduire dans la zone de notification à la fermeture d’Atlas Launcher"] = "Minimize to the notification area when closing Atlas Launcher",
            ["Installation du jeu"] = "Game installation",
            ["DOSSIER DU CLIENT"] = "CLIENT FOLDER",
            ["Configuration du jeu"] = "Game configuration",
            ["Langue du jeu"] = "Game language",
            ["Texte de quête instantané"] = "Instant quest text",
            ["Disponibilité des mises à jour Atlas."] = "Atlas update availability.",
            ["Atlas Launcher"] = "Atlas Launcher",
            ["ATLAS LAUNCHER"] = "ATLAS LAUNCHER",
            ["VERSION INSTALLÉE"] = "INSTALLED VERSION",
            ["VERSION DISPONIBLE"] = "AVAILABLE VERSION",
            ["Rechercher les mises à jour"] = "Check for updates",
            ["Connexions des amis"] = "Friend connections",
            ["Nouvelles demandes d’amis"] = "New friend requests",
            ["Toujours activées"] = "Always enabled",
            ["Journaux locaux"] = "Local logs",
            ["Ouvrir les journaux"] = "Open logs",
            ["Rapport de diagnostic"] = "Diagnostic report",
            ["Copier le rapport"] = "Copy report",
            ["Dossier du launcher"] = "Launcher folder",
            ["Outils"] = "Tools",
            ["État et versions"] = "Status and versions",
            ["État local"] = "Local status",
            ["État des services"] = "Service status",
            ["Client WotLK Classic"] = "WotLK Classic client",
            ["Atlas Launcher · portable"] = "Atlas Launcher · portable",
            ["Preview fictive"] = "Mock preview",
            ["Notification locale"] = "Local notification",
            ["Ami connecté"] = "Friend online",
            ["Nouvelle demande d’ami"] = "New friend request",
            ["est maintenant en ligne."] = "is now online.",
            ["souhaite t’ajouter à ses amis."] = "would like to add you as a friend.",
            ["Plusieurs amis viennent de se connecter."] = "Several friends just came online.",
            ["Plusieurs nouvelles demandes d’amis sont arrivées."] = "Several new friend requests have arrived.",
            ["À jour"] = "Up to date",
            ["À réparer"] = "Repair needed",
            ["Non installé"] = "Not installed",
            ["Non vérifié"] = "Not verified",
            ["Non vérifiée"] = "Not checked",
            ["Jamais"] = "Never",
            ["Disponible"] = "Available",
            ["Aucune"] = "None",
            ["Recherche en cours"] = "Checking for updates",
            ["Mise à jour en cours"] = "Update in progress",
            ["Réparation en cours"] = "Repair in progress",
            ["Analyse du client local…"] = "Scanning local client…",
            ["Analyse des fichiers locaux…"] = "Scanning local files…",
            ["Analyse des fichiers nécessaires"] = "Scanning required files",
            ["Analyse complète du client"] = "Full client scan",
            ["Analyse en arrière-plan"] = "Background scan",
            ["Analyse terminée"] = "Scan complete",
            ["Comparaison des fichiers…"] = "Comparing files…",
            ["Chargement du manifeste…"] = "Loading manifest…",
            ["Manifeste reçu"] = "Manifest received",
            ["Préparation du client"] = "Preparing client",
            ["Préparation des fichiers"] = "Preparing files",
            ["Préparation du redémarrage"] = "Preparing restart",
            ["Préparation du redémarrage…"] = "Preparing restart…",
            ["Préparation de l’opération…"] = "Preparing operation…",
            ["Préparation…"] = "Preparing…",
            ["Téléchargement du client"] = "Downloading client",
            ["Téléchargement de la réparation"] = "Downloading repair",
            ["Téléchargement des fichiers manquants"] = "Downloading missing files",
            ["Téléchargement des fichiers à réparer"] = "Downloading files to repair",
            ["Téléchargement des fichiers du client"] = "Downloading client files",
            ["Téléchargement de l’addon"] = "Downloading addon",
            ["Téléchargement d’Atlas Launcher…"] = "Downloading Atlas Launcher…",
            ["Téléchargement de la nouvelle version…"] = "Downloading new version…",
            ["Téléchargement annulé"] = "Download cancelled",
            ["Application de la mise à jour"] = "Applying update",
            ["Application de la réparation"] = "Applying repair",
            ["Application des fichiers réparés"] = "Applying repaired files",
            ["Application des fichiers réparés…"] = "Applying repaired files…",
            ["Écriture des fichiers du client"] = "Writing client files",
            ["Enregistrement de l’installation"] = "Saving installation",
            ["Nettoyage des anciens fichiers…"] = "Cleaning old files…",
            ["Nettoyage terminé"] = "Cleanup complete",
            ["Finalisation de l’installation…"] = "Finishing installation…",
            ["Finalisation…"] = "Finishing…",
            ["Redémarrage en cours"] = "Restarting",
            ["Arrêt de l’opération en cours…"] = "Stopping current operation…",
            ["Opération en cours"] = "Operation in progress",
            ["Opération interrompue"] = "Operation interrupted",
            ["Opération annulée"] = "Operation cancelled",
            ["Opération annulée."] = "Operation cancelled.",
            ["Installation terminée"] = "Installation complete",
            ["Mise à jour terminée"] = "Update complete",
            ["Vérification terminée"] = "Verification complete",
            ["Réparation terminée"] = "Repair complete",
            ["Installation échouée"] = "Installation failed",
            ["Mise à jour échouée"] = "Update failed",
            ["Vérification échouée"] = "Verification failed",
            ["Réparation échouée"] = "Repair failed",
            ["Suppression échouée"] = "Removal failed",
            ["Vérification annulée"] = "Verification cancelled",
            ["Réparation annulée"] = "Repair cancelled",
            ["Suppression annulée"] = "Removal cancelled",
            ["Terminé"] = "Complete",
            ["Installé"] = "Installed",
            ["Mis à jour"] = "Updated",
            ["Réparé"] = "Repaired",
            ["Supprimé"] = "Removed",
            ["Réparer"] = "Repair",
            ["Installation…"] = "Installing…",
            ["Mise à jour…"] = "Updating…",
            ["Réparation…"] = "Repairing…",
            ["Suppression…"] = "Removing…",
            ["Progression indéterminée"] = "Progress unavailable",
            ["Cette action attend la fin de l’opération en cours."] = "This action is waiting for the current operation to finish.",
            ["Une autre opération Atlas est déjà en cours."] = "Another Atlas operation is already in progress.",
            ["Une autre opération est déjà en cours."] = "Another operation is already in progress.",
            ["L’opération n’a pas pu être terminée."] = "The operation could not be completed.",
            ["L’opération n’a pas pu être terminée. Consulte le diagnostic."] = "The operation could not be completed. Check diagnostics.",
            ["Le téléchargement n’a pas pu être terminé."] = "The download could not be completed.",
            ["Le téléchargement n’a pas pu être terminé. Tu peux réessayer ou ouvrir le diagnostic."] = "The download could not be completed. Try again or open diagnostics.",
            ["Le téléchargement a pris trop de temps. Réessaie."] = "The download took too long. Try again.",
            ["Atlas n’a pas accès au dossier du jeu."] = "Atlas cannot access the game folder.",
            ["Tu peux jouer pendant l’analyse"] = "You can play during the scan",
            ["En arrière-plan"] = "In the background",
            ["Actualisation…"] = "Refreshing…",
            ["Actualisation des amis…"] = "Refreshing friends…",
            ["Actualisation du profil…"] = "Refreshing profile…",
            ["Restauration de la session…"] = "Restoring session…",
            ["Déconnexion en cours."] = "Signing out.",
            ["Demande d’ami envoyée."] = "Friend request sent.",
            ["Demande d’ami acceptée."] = "Friend request accepted.",
            ["Demande refusée."] = "Request declined.",
            ["Demande envoyée annulée."] = "Sent request cancelled.",
            ["Ami retiré de ta liste."] = "Friend removed from your list.",
            ["Envoi de la demande…"] = "Sending request…",
            ["Acceptation de la demande…"] = "Accepting request…",
            ["Refus de la demande…"] = "Declining request…",
            ["Annulation de la demande…"] = "Cancelling request…",
            ["Retrait de l’ami…"] = "Removing friend…",
            ["Annuler l’envoi"] = "Cancel request",
            ["Une demande est déjà en attente."] = "A request is already pending.",
            ["Ce compte fait déjà partie de tes amis."] = "This account is already in your friends list.",
            ["Tu ne peux pas t’ajouter toi-même."] = "You cannot add yourself.",
            ["Cette demande n’est plus disponible."] = "This request is no longer available.",
            ["Reconnecte-toi pour gérer tes amis."] = "Sign in again to manage your friends.",
            ["Saisis un nom d’utilisateur Atlas valide."] = "Enter a valid Atlas username.",
            ["Chargement du catalogue…"] = "Loading catalog…",
            ["Le catalogue Atlas n’est pas encore disponible."] = "The Atlas catalog is not available yet.",
            ["Le catalogue Atlas n’a pas pu être chargé."] = "The Atlas catalog could not be loaded.",
            ["Le catalogue Atlas n’a pas pu être actualisé. Les informations affichées sont conservées localement."] = "The Atlas catalog could not be refreshed. Displayed information was kept locally.",
            ["Atlas récupère les informations disponibles."] = "Atlas is retrieving available information.",
            ["Aucun addon ne correspond à ce filtre."] = "No addon matches this filter.",
            ["Modifie la recherche ou le filtre sélectionné."] = "Change the search or selected filter.",
            ["Tout mettre à jour"] = "Update all",
            ["Tous les addons disponibles ont été mis à jour."] = "All available addons have been updated.",
            ["Installation externe détectée"] = "External installation detected",
            ["Aucune version installée"] = "No version installed",
            ["Aucun dossier déclaré"] = "No folder declared",
            ["Aucune dépendance requise"] = "No dependencies required",
            ["Détecté (non géré)"] = "Detected (unmanaged)",
            ["Reconnecte-toi pour gérer tes addons."] = "Sign in again to manage your addons.",
            ["Installe d’abord le client WotLK pour gérer ses addons."] = "Install the WotLK client first to manage its addons.",
            ["Installe d’abord le client WotLK."] = "Install the WotLK client first.",
            ["Cet addon n’est plus présent dans le catalogue."] = "This addon is no longer in the catalog.",
            ["Impossible de télécharger cet addon pour le moment."] = "This addon cannot be downloaded right now.",
            ["Atlas n’a pas pu écrire les fichiers de cet addon."] = "Atlas could not write this addon's files.",
            ["Certains fichiers de l’addon sont utilisés par une autre application."] = "Some addon files are being used by another application.",
            ["Addon installé."] = "Addon installed.",
            ["Addon mis à jour."] = "Addon updated.",
            ["Addon réparé."] = "Addon repaired.",
            ["Addon supprimé."] = "Addon removed.",
            ["Photo de profil actualisée."] = "Profile picture updated.",
            ["Préparation de la photo…"] = "Preparing picture…",
            ["Envoi de la photo…"] = "Uploading picture…",
            ["Traitement par Atlas…"] = "Processing with Atlas…",
            ["Suppression de la photo en cours…"] = "Removing picture…",
            ["Cette image ne peut pas être utilisée."] = "This image cannot be used.",
            ["L’image dépasse la limite de 25 Mo."] = "The image exceeds the 25 MB limit.",
            ["Le recadrage de cette image n’est pas valide."] = "This image crop is invalid.",
            ["Une modification de photo est déjà en cours."] = "A picture change is already in progress.",
            ["Atlas n’a pas pu traiter cette photo."] = "Atlas could not process this picture.",
            ["La photo n’a pas pu être modifiée. Réessaie."] = "The picture could not be changed. Try again.",
            ["L’état de la photo n’a pas pu être confirmé. Actualise le profil."] = "The picture status could not be confirmed. Refresh the profile.",
            ["Termine l’opération en cours avant de modifier ta photo."] = "Finish the current operation before changing your picture.",
            ["Sélectionne de nouveau la photo avant de l’utiliser."] = "Select the picture again before using it.",
            ["Le fichier sélectionné n’est plus disponible."] = "The selected file is no longer available.",
            ["La photo n’a pas pu être préparée. Réessaie avec une autre image."] = "The picture could not be prepared. Try another image.",
            ["Cette adresse e-mail est déjà utilisée."] = "This email address is already in use.",
            ["Ta session Atlas a expiré. Reconnecte-toi."] = "Your Atlas session has expired. Sign in again.",
            ["Ta session Atlas doit être renouvelée."] = "Your Atlas session needs to be renewed.",
            ["Cette session n’est plus active."] = "This session is no longer active.",
            ["Trop de tentatives. Réessaie dans quelques instants."] = "Too many attempts. Try again shortly.",
            ["Atlas met trop de temps à répondre. Réessaie."] = "Atlas is taking too long to respond. Try again.",
            ["Atlas n’a pas pu appliquer cette modification."] = "Atlas could not apply this change.",
            ["Cette modification n’a pas pu être appliquée. Réessaie."] = "This change could not be applied. Try again.",
            ["Adresse e-mail modifiée. Un message de validation a été envoyé."] = "Email address changed. A verification message was sent.",
            ["Adresse e-mail modifiée. Le message de validation n’a pas pu être envoyé."] = "Email address changed. The verification message could not be sent.",
            ["Un message de validation a été envoyé."] = "A verification message was sent.",
            ["Mot de passe modifié."] = "Password changed.",
            ["Appareil déconnecté."] = "Device disconnected.",
            ["Termine l’opération en cours avant de modifier ton compte."] = "Finish the current operation before changing your account.",
            ["La session locale a été fermée, mais la déconnexion n’a pas pu être confirmée."] = "The local session was closed, but sign-out could not be confirmed.",
            ["La déconnexion a expiré. Réessaie dans quelques instants."] = "Sign-out timed out. Try again shortly.",
            ["Atlas a refusé la déconnexion. Ta session reste active."] = "Atlas rejected sign-out. Your session remains active.",
            ["La session locale n’a pas pu être supprimée."] = "The local session could not be removed.",
            ["La déconnexion n’a pas pu être terminée. Réessaie."] = "Sign-out could not be completed. Try again.",
            ["Le démarrage avec Windows n’a pas pu être modifié."] = "Start with Windows could not be changed.",
            ["La préférence n’a pas pu être enregistrée. La valeur précédente est conservée."] = "The preference could not be saved. The previous value was kept.",
            ["Préférence enregistrée sur cet ordinateur."] = "Preference saved on this computer.",
            ["Modifications non enregistrées"] = "Unsaved changes",
            ["Les changements de cette catégorie n’ont pas encore été appliqués."] = "Changes in this category have not been applied yet."
        };

    private static readonly IReadOnlyDictionary<string, string> FrenchByEnglish =
        EnglishByFrench
            .GroupBy(pair => pair.Value, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => group.First().Key, StringComparer.Ordinal);

    private static readonly (string French, string English)[] EnglishFragments =
    [
        ("Dernière actualisation réussie à ", "Last successful refresh at "),
        ("Données précédentes conservées · actualisation indisponible.", "Previous data retained · refresh unavailable."),
        (" Atlas · actualisation indisponible", " Atlas · refresh unavailable"),
        ("Hors ligne · vu hier à ", "Offline · seen yesterday at "),
        ("Hors ligne · vu le ", "Offline · seen on "),
        ("Dernière activité le ", "Last active on "),
        ("Créée le ", "Created on "),
        ("Aujourd’hui à ", "Today at "),
        (" · niveau ", " · level "),
        (" appareils connectés", " connected devices"),
        (" appareil connecté", " connected device"),
        (" fichiers analysés", " files scanned"),
        (" fichier analysé", " file scanned"),
        (" dossiers gérés", " managed folders"),
        (" dossier géré · ", " managed folder · "),
        ("Version installée  ", "Installed version  "),
        ("Dépendances · ", "Dependencies · "),
        ("Installés  ", "Installed  "),
        ("Mises à jour  ", "Updates  "),
        ("Aucun addon trouvé pour “", "No addon found for “"),
        ("Installation de ", "Installing "),
        ("Mise à jour de ", "Updating "),
        ("Réparation de ", "Repairing "),
        ("Suppression de ", "Removing "),
        ("Envoi de la photo… ", "Uploading picture… "),
        ("Envoi… ", "Uploading… "),
        (" s restantes", " s remaining"),
        (" min restantes", " min remaining"),
        ("quelques secondes", "a few seconds"),
        ("environ ", "about "),
        (" · données conservées", " · data retained"),
        (" Utilise /reload dans le jeu pour l’activer.", " Use /reload in game to enable it."),
        (" en jeu sur ", " playing in ")
    ];

    private static string _currentLocale = FrenchLocale;

    internal static event EventHandler? LocaleChanged;

    internal static string CurrentLocale => Volatile.Read(ref _currentLocale);

    internal static bool IsEnglish => string.Equals(
        CurrentLocale,
        EnglishLocale,
        StringComparison.OrdinalIgnoreCase);

    internal static void SetLocale(string? locale)
    {
        string normalized = LauncherSettings.NormalizeInterfaceLocale(locale);
        bool changed = !string.Equals(
            CurrentLocale,
            normalized,
            StringComparison.OrdinalIgnoreCase);
        CultureInfo culture = CultureInfo.GetCultureInfo(normalized);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;
        Volatile.Write(ref _currentLocale, normalized);
        if (changed)
        {
            LocaleChanged?.Invoke(null, EventArgs.Empty);
        }
    }

    internal static string Text(string? source)
    {
        if (string.IsNullOrEmpty(source))
        {
            return source ?? string.Empty;
        }

        IReadOnlyDictionary<string, string> catalog = IsEnglish
            ? EnglishByFrench
            : FrenchByEnglish;
        return catalog.TryGetValue(source, out string? translated)
            ? translated
            : source;
    }

    internal static string TranslateFromFrench(string source)
    {
        ArgumentNullException.ThrowIfNull(source);
        if (EnglishByFrench.TryGetValue(source, out string? exact))
        {
            return exact;
        }

        string translated = source;
        foreach ((string french, string english) in EnglishFragments)
        {
            translated = translated.Replace(french, english, StringComparison.Ordinal);
        }

        if (translated.StartsWith("Last active on ", StringComparison.Ordinal)
            || translated.StartsWith("Offline · seen on ", StringComparison.Ordinal))
        {
            translated = translated.Replace(" à ", " at ", StringComparison.Ordinal);
        }

        return translated;
    }

    internal static string Format(string frenchFormat, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Text(frenchFormat), arguments);
}
